apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-shared-pv
  namespace: atlassian
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: jira-efs-sc
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
    - lookupcache=pos
    - noatime
    - intr
    - _netdev
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <EFS-ID>:<PATH>